apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:cEYkgFOQ/Cv8SWW15hyIWGbcbfGeUJfuD8McNpO2YANH308S,iv:G5jy4veqoJIgjjsQ83ujPBHCoo6fUWuBu9QIoohSS5c=,tag:78Lu+VwEY6lATiJjrVl6nQ==,type:str]
  credentials.json: ENC[AES256_GCM,data:eQiUT3XgSUjrTLMXu59ZLdCrIHVXcWMkO5uRf/ayzsqG6f2C/u6aWCcyyTmQWZVzyTtFfgRtSSa1e2Ka81/fcUSPMFS+D9bcrJPwkQPk4lm+k2y0ri6fwpz456bKzpOaxVhIfUxV8vYlQN7sOCvMgW0Urn1g9i9WwSbclgH+CtvD6ppYCScZpV5x/Deq/nVx35UNDmMT1WcwN7mBPiv4A0oaWu+Bk4tHi9NE,iv:KS/xmQ1wR0/KmmwE/M1q3Q65QShjwlkZPPgI2WlC2Xc=,tag:FI47W1xh6f+623MJ4kYW7g==,type:str]
sops:
  age:
    - recipient: age1ds3pve0r242jp4ktktmx9n3gap5tt37tp3reehtrqp0z0m4ncy7sce4qc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ODBRYXpLc0wzODAra2dD
        TlhYQ1dnR2RPbFh1L1dVMVI0NnE4YXNEZ1c4CjFMQnp0azBZMWZnUVZ0QURMQlZD
        UDNwenNxQmdjY2ZnekJySmE5eTlNdFEKLS0tIHZNQytHOGlSbFM2V3c2TG5ad3Yy
        TW40dzl3L1NzRElUVGhpaHpxaDdGMk0K12lrnPAZPKZK1/ooFHFn6WMZQ1e5mMBN
        pNt5t5H0VHxumgpHG5p5+RrrhmIBwDE6mV3BFPY3tRhqXvBvKvUSLg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-14T05:28:03Z"
  mac: ENC[AES256_GCM,data:ssYYD09/VMvQWvRRo3WNx7b4a+5tn9mYMsGr//yrDB+IBn3o4lrpYWTvUp9yRdSH4ZXgUq3rOK2oQ/gN9iUb0+9JPluyOIbaHzeLa2YmKBeUJFUJEenbu6P6572JjJ/nmEvNnzQnvwDCjMhLsa8Jt+2AYy/LO1vLqL7RTYj7wQI=,iv:TYPpg2Czs73eFQ0Hf/4xF+bF6orNangaCssSfJNnClU=,tag:26BtezuVZGpZlyLCLR5bPA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
