# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:z4rBrOZ21qU3yOeWQzTW8MZBU/jTESBs2hZNsrNw+N3Ar43P9Cr2v2y55IlMJCUuid0Qn/AizkKKbtQvmSiqfxLY/Og+7YVxyAr/LpAvLID7K6FsTwa9+7yqvHdzCIZzlVYHSCFIwQTPGG0HlTRtXIFh3hs/364KZXj8wcQT/KoVHCS87IH+pz6miq2Ati2xg12t5VkwTQfWJPIbl1+1OTx25Jq4IlBH/UgMwXF0OthD0adfGg==,iv:OxcdzJAmYxM6KbwVidpE/xu++rR6AvvNbfEIsJfi90o=,tag:fidRYoLYa0ZuWeAml6TrLA==,type:str]
sops:
  age:
    - recipient: age1w6awdq3uyjjy9spqc6va5w8m2zfxaa9v7gd43608z2grzcqsef8sagk2yh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWDRqa1hhZWJlTHQzZjg2
        WElVek93ZFRxd3V4SzJQY0Vra0JOcUpGZFRrClJNb2R4MGRRNlBSaDU2eUkzVXNy
        WjJLLzkvZ0tYdFVmZmlNYUNCY2J1ZTgKLS0tIGh4a2pDeU9pb09kNzNaUkZMN09l
        QmNvbW0xWGxjQ0Q3bWtDZVdGaHBiRUEKQj8ulbXdftuYQXCcdlHXs1p+6h+hxZZj
        z81HXOEAIgyguiygzWyuPqcHqwg09gybkm6grQUZFlwTH7S2jQsqYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-08T05:05:28Z"
  mac: ENC[AES256_GCM,data:nujFiNX6U+tTKBZvzNpfsUvxInvNq8v26cXuGHKiU5ejcYvLd+QFkTkAeGdGoHf9ghvQtc8cqEc3+U9kjyO61vct/wHbePTjYp7ab0IBz5B9vwYG2kPwhb5BkuczGs1F94vOmwq4r4wLqZAD/8UrTmYcl3c2hQNBARMlCBGo1Ro=,iv:GlHUX0kIg7GjCdq1YyGgSbmSdGBqsRHS9J4JYCxdyfw=,tag:SVU0BtL0jWblgWXwOdS9cQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
