---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
components:
  - ../../components/common
resources:
  - ./cifs-pvcs/ks.yaml
  - ./plex/ks.yaml
  # - ./overseerr/ks.yaml
  # - ./romm/ks.yaml
