- Infrastructure:
    - {{ .QNAP_NAME }}:
        icon: qnap
        href: {{ .QNAP_URL }}
        description: QNAP {{ .QNAP_MODEL }}
        widget:
          type: qnap
          url: {{ .QNAP_URL }}
          username: {{ .QNAP_RO_USER }}
          password: {{ .QNAP_RO_PASS }}
    - {{ .SYN_NAME }}:
        icon: synology
        href: {{ .SYN_URL }}
        description: Synology {{ .SYN_MODEL }}
        widget:
          type: diskstation
          url: {{ .SYN_URL }}
          username: {{ .SYN_RO_USER }}
          password: {{ .SYN_RO_PASS }}
          volume: volume_1
    - {{ .UNIFI_NAME }}:
        icon: unifi
        href: {{ .UNIFI_URL }}
        description: UNIFI {{ .UNIFI_MODEL }}
        widget:
          type: unifi
          url: {{ .UNIFI_URL }}
          username: {{ .UNIFI_RO_USER }}
          password: {{ .UNIFI_RO_PASS }}
- Observability:
    - Cloudflared:
        href: https://dash.cloudflare.com/
        icon: cloudflare-zero-trust
        description: Cloudflared Tunnel Status
        widget:
          type: cloudflared
          accountid: {{ .CF_ACCOUNT_ID }}
          tunnelid: {{ .CF_TUNNEL_ID }}
          key: {{ .CF_API_TOKEN }}
    - Gluetun:
        icon: gluetun
        description: Gluetun VPN Gateway
        namespace: network
        app: pod-gateway
        widget:
          type: gluetun
          url: http://vpn-gateway.network
          fields: ["public_ip", "region"]
- Calendar:
    - Agenda:
        widget:
          type: calendar
          view: agenda
          maxEvents: 20
          integrations:
            - type: sonarr
              service_group: Downloads
              service_name: Sonarr
            - type: radarr
              service_group: Downloads
              service_name: Radarr
            - type: readarr
              service_group: Downloads
              service_name: Readarr
