# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:NZm4frLCizeO8c2lGa3oQdXxv4HTHRpV1ttc3aRtCMsW1JqaoAN1RA==,iv:eftIxnqj7VzhKDMZlyswRjlyz6KXcuJNkjkmKo7jYso=,tag:E/Zqqa1WyyM0dkrIinua2Q==,type:str]
sops:
  age:
    - recipient: age1w6awdq3uyjjy9spqc6va5w8m2zfxaa9v7gd43608z2grzcqsef8sagk2yh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCR1NpNFk2RUtzaWpsM2NK
        cXA1Z1Z5R0kzUCtBa1F2bkluQUNJWDBSTjFNCnZXWnhzYkdEb2dDSEVJUy90RzlM
        R3JuNWNvVFhnZ1VVdTFTdzBCQjA3RlUKLS0tIHRhN3VZN005ZURSMVIxQk13RUFM
        UXA2WXN6eGhPWGJIL1ZnYjU3Nkp6K0UKgPNuNtL4FJd+HSqGNTiUQRjiAF8sVJ1G
        mfV5NxxtMohSLh39xLw7MmgB2v193WTnr/hxkpnQn9xXJiJZCtpftA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-08T05:05:28Z"
  mac: ENC[AES256_GCM,data:SnnqvR/lk/SXxEl07A6Bn2cu2DMPjuKyV2qj3Lz+wuZYhYddESA9kqYLsjH9/KvuBIDBDXDWbE9CgSWmjF1nShl9UYwCE93L+kWspfKAYL4TeRCppVPKPgTcfbZHc35F6VLxTM5vlHAsp+4A3IvrV7xV+fAiR2W/q+aa/YMaIEs=,iv:nJJUXudkZLqSrfe/8fy+BOS8YFQEKxejY+jkPxkyIyw=,tag:BWOesz3ZIpjJmpH0yMKUEw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
