# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.32.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:qg/oewomAG7Mf2T0zSkMUMnH/kJRMqdsNyOxtD2lKa6UlFi0MqIiLA==,iv:oVizYnozO5fAkyF4zezQiPV1bG27iR15GoBZqa0sJGI=,tag:L8GD0sAi11h6nHiG5Fa5uw==,type:str]
sops:
  age:
    - recipient: age1ds3pve0r242jp4ktktmx9n3gap5tt37tp3reehtrqp0z0m4ncy7sce4qc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFL3RSV25XdjFpakk0REVB
        SXgzV3NzajZYaHRISmEzbzJaYUd3Nk1aOGdJCi9RV2FWQ1o1VWR1Y3FEcmcydC8z
        bXJzSXV1NVkxWW1vNi9uZ0RsUjNCTXMKLS0tIE1jbk14RmQxUEdxSDdRYmZuN1dY
        Vi9qRHhsZWpIOHFWSWFxKzJXcCtKaVUKXgOFuSOEqshbKcO4xf5oEsOg0UWVky6w
        4e/6J5f2sz1nXfDImOAoqpC2y9GOr3xMYtCDjXYDufpW1gtR9N5f6w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-14T05:24:39Z"
  mac: ENC[AES256_GCM,data:+6PAIL2TyBw4iWaeumNcrzm6X1ec5F5QqhzYkihv87Cga9+5ubKDwZhTJfIHY60RX+ZRvT4cbaE0qC0+R4J+m21aEKHlh5KxQ9IG6UEmKU43x3+AWnLmCy0FZZXGx/wTaTVxWZMHwSQ4KmtRif19MjG7IoP1AeTX9G824TFCRXU=,iv:TZ48K0RYpA55u8wMPlkeYUUfhK6sfRC68m6XZr3psfs=,tag:DejuVZoMyf04IE5cjQc6WA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
