apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Xm192y2SLcqjQN/POWOlKJTAORIgTB1C1AGO0xwGkcF5nrav,iv:UQYpGkcBrE+kpTWXHYz0v3gEcAJofbvVKUxKfaH7l9A=,tag:A7Cq+d2c4W2mjyFAHQ74NQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:gWmEozX/f3ihzP7J+Cvkx9vr6rQgaOMWT/km0jsPiZ3syF5c8Pj8oXM71YdybnKRenneyKvuc4kydVju5ax36RYJVoPKwYSSvQPhpnCMS7BAGQFMNXQud2rzloxHxLE21ogmyYiSuv3QZ00tO/3hMCOemkdUwSQg9H3nQP3hRS2p/935J1VbVakSMG8Ih+0Zw6PY9tSBJHMeFn/PQitam1kxuOByMYw2VHwWM2bCbA==,iv:cA/ZxVP2/OT3L59zr6QyyBA3l6y2y27/xZnoVVMJHVc=,tag:ZoafzyRBD0HsLuyQN6x6Og==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmv82du5pq7cddh65lfmwvg3v4ju3pyf99qhnzmhw53mt86vlpyq7ugstq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSVFJMkM1RkFScW9VZjB0
            bUs2bHRsTTZzdWFuWVoxUUlxNXJiTVAxbmxnClYyVnkydzlsWDAxOUxOVHZ6QjMr
            Zk1GTXI0eEtwUGtaQzJKRkpxQlArWDQKLS0tIGNEeGJJZFdxODM5cXlNWUs2aXpJ
            UEZNaVBSNytORlFyWHRKUTNLb0xEOEEK2Yb0mT778iaL1CWEBA7CZuhLyZbFX+TK
            7V1j3riMrECGDIvabvUfyYXUr+s9srBVcNoZ8l6dkzFZ8uUaeQKP5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-27T01:14:24Z"
    mac: ENC[AES256_GCM,data:nfuz4RrJZ6OipQQAECRY0pGp9PvFRAlnBcAMKGtuCjSxBUdVSfAw6JwD6wmRIPA8k98oULfoVayj3UWeS04Ck828lKY/TTshyzRoXVImsqAefsz/7q3RWB9vCemiDxx5iDKkqpjfarz27PN0QiQHciiI15OpHn2oDlto/iYe44k=,iv:cucwcpznGUmvLCKVtmLg9M38sXwwq1zZ/vPRiN5rZE8=,tag:UG8Sn0J1sXMUFpv0DjJbFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
