# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:az2Mw/TMe+9LU/+OJjYO/SJTocr7Kol9juS7HljtnxMeDqkljhVX8Q==,iv:n85zeOJflvuCTNeZCWguFkGp5S6x8SDPG1hC7EvuUs4=,tag:FECeQC1Vcb308OCAyEcmPg==,type:str]
sops:
  age:
    - recipient: age1ds3pve0r242jp4ktktmx9n3gap5tt37tp3reehtrqp0z0m4ncy7sce4qc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6L2VKcFpkbml6alpyTFE1
        RXNKV21hOFo2SkpPTVUxaERrOVhxZXR2NFNVCjMxdHd5b0syeVlobmx2UDhEZEdi
        dTAxVU5kaGYxZ24xblNPRU02OHg2TzQKLS0tIFBwVFRVTVVLSjIyajNSUXZSSXJS
        eUllQmN0YzcveWwrWWlFanRiYXJOMVUKxZ6U6a74XrE3Vrdl6LWETD4hGj7fAHUw
        5EuiL5ytnHa6Xj3YPPJMC0Hc7RMBBgWz8+j0H+rrTxYepKc0XAKBVA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-13T17:26:46Z"
  mac: ENC[AES256_GCM,data:oLxdp4JKH1NjWP+bJ5B7ER+Qx9rcqc9aDytMCsUJlOBoO1TmHZ41Kz8hqxshBwsFDueHGUSBJhoq3kDMFi/KR5G9XUIu/DRrO1jzAi9u7NZhZDqzjxAQVf3HBywCzWL1SuMg22S/N5y2lx9QFg9YcHzadXf7InuzXfSOFs7fBAs=,iv:GwTGQZMULJQ7YFoOr4tu2k+HkxMkejuoVPrCZTQqKfQ=,tag:CFehPJEIe08hzYYGlVQYRw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
