# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:F3Wx/cU+a10jjtq3jC1iLpHp83RVsrNdww+FXXN/mR8XidpvtBbYpg==,iv:Qz4ODAaLr5KSU6wvQlcXFKmZMxe4it07dlkYId7TBNM=,tag:hldgrOye4hGyAYWjkNW7OQ==,type:str]
sops:
  age:
    - recipient: age1ds3pve0r242jp4ktktmx9n3gap5tt37tp3reehtrqp0z0m4ncy7sce4qc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTL0NndytUN3FLRForSXhj
        YjErYWF2ZHVLYVRxTC82RnI0bXdaT0hmempFClVRQk1qN2h0WnlWakZyS3RwL0da
        ZktHbFJPZDlOWUxEa3lTcjFrbkQ4elkKLS0tIEdZQVg1V1ZrMmFPSDRHZ01Id3N0
        OTdoS3h1aVZQRHZBOFVhRWRTSWUvTlEKADxd64rVhhLsDZESh+oloQjq/rZ7UCJu
        frsHRUskLfy0J7VD22MIr4Abe9N2B1r2i5AbToDslaDu0gpCohGkWw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-13T18:08:16Z"
  mac: ENC[AES256_GCM,data:Pa6z3hs+WSR5JBXC30c7xj5Dm/PU//IUzWe+440DkcfCQteSJcsDtUPR3rifh+IXECVNV2fT9eAyYWdsrOUR4Z5jyVLA6rMJ6LmtWj0qCpDh1TwKXsUmhBB/NSdZZodEospzCgM4Y53XVwaNMIfI+rS44zFO+exam/tUWe3lBIY=,iv:WaY96xrP04T4vbxhbwl61tI3KWZ13ffn0CZ0fAXObNA=,tag:IMKX3Kiyx00yaRz82ASMAQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
