# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:c5GbV2rB9HjV8ipEdEFNY1lUq97VQYe01CG1zxl8LVPwS8MuCKrJfQ==,iv:F7HsrkfmsTeu+/kK/CvJUsyQ409arPX7QBAjCMMOqTw=,tag:yFEk8nwCZdzzla74htu3dg==,type:str]
sops:
  age:
    - recipient: age1w6shr02fugn7ys2cz75f8sq4qcmzuwa6wfwgzx69203zpdaj73ys0ay2ee
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNTZkUHN6SGZtcWh5Q1By
        SWhVSy90SUN1TlkyeXpIbEFhQjV1N2s4N21zCjU0OVVBYzJKRjNYL282MWp3YXJm
        Z3VtSEFNYmE1amRhd2JDRkRYQXlBeU0KLS0tIEk5M3JOcTlqN3cxQ3Jha3BHbHJP
        TW1qTTNxSGk0YjhDclNjRG8rM240L00KoqLxrBR1RpPNbXw+NJ3gtZModrhiY8OE
        K2BhpBc4gjzenYymU7o0yGw9SbUalqngTn8gEjnQF261w2A1eXw7Dw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-19T06:16:31Z"
  mac: ENC[AES256_GCM,data:7fEOGXBey3iCE7DyhLbxJZ/mhQeIrUrES16dCVRVDzmW6ikEd6HeTo/IS2LDdL4/fdlZJWSJt56zjIlDtJTiHCCNe3+BngJInBJbKY4mcexpTEEyCquY8Ao9gfU/AztJnAE4/55Q8vK0r6G/IqWgIVjU3EIKkPLK2QylpTSINzg=,iv:miRWLipnLexho9wpnx2kFfWUcBT8jzoJYg7ebY+UUTA=,tag:K56kjwnAh2yKUi/Q6OO1XQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
