apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:vHxnTTzPpaxPVHsgjTdLR/gfYllK7GCwfnZs4aX79Dg=,iv:RETYsa9a2vzrXJX01Wst1bmD+UVoLnctZeyWajphdXM=,tag:bob6fjCa1OJHa0X8LNRt+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmv82du5pq7cddh65lfmwvg3v4ju3pyf99qhnzmhw53mt86vlpyq7ugstq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQWp6ejY4SmlDd0plNW83
            cTBLZGd5MDNON0Uvc1Jmc0pHaHJyT0JKMjM0CkNSaW5YUjN4d0NhNEZ2cE5zNDFh
            MUM5cldWNG4xaU9HK0trazMrOVpEeU0KLS0tIEg2UTA2d0YzVi9iOW9hK214YlVz
            THlEcElTdFhXSDhqS08rZHhaWWV4NE0KlCGDHDQMTBYcQaUCdBpUSEt2rH9VLo/k
            M+ONdCLlJJYvuazRH2TKjXhjBv3y99kXyMckrDfmUmFOz0CbKdJ5iQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-27T02:42:42Z"
    mac: ENC[AES256_GCM,data:J3UoL2OWn7xw+LdfGXxPPAPernVSNntzqCusbRiifDcwAOTI4A0yBHSbC1DroWJNwwQQ/8C0Sv6oTSKQ+pAp6KmpuB0uHs0BjvtxFH/FcY1kyxIz6igZGlNCTfiVRO5/lRTxblGnftHgNE0+Y+7NkPlmo/2/cpK/dbUL3UUKMFw=,iv:7FCeQFvlu7sUix6jdjCW9aIjBZ9e6Kv7mnOggNoJj6o=,tag:R5X4owhTNrrFYWGmcVfH+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
