---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PGAdmin
metadata:
  name: pgadmin
spec:
  users:
  - username: admin@devilfruitlabs.com
    role: Administrator
    passwordRef:
      name: pgadmin-secret
      key: PGADMIN_PASSWORD
  dataVolumeClaimSpec:
    storageClassName: openebs
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  serverGroups:
    - name: Crunchy Postgres
      postgresClusterSelector: {}
  serviceName: pgadmin
