# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Z+Qp3lBORjz2QMF15wBSmhlOhFt2yvIjLcV5Yl4k4GQ=,iv:leVlH6frUN342ypshfiab2kF5OkcZr6Rq080uj3UhGw=,tag:MyuhxpFbHgxIplZnxjDl8A==,type:str]
sops:
  age:
    - recipient: age1w6shr02fugn7ys2cz75f8sq4qcmzuwa6wfwgzx69203zpdaj73ys0ay2ee
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUFY1bHY2YWttTG14eTNo
        d3VOVVpEc0dGK2lobTJSeDVZZVlFUkNaR1h3Cis5UTB6Q3VodXRLQ0JXaHVKcnIv
        MkpuNWxycllBaWNybWJDVGp1VHFkemcKLS0tIFp4enJrUWJ2QjRXMFFBRzJKbzFD
        a1VzSWEyUlBEQ2hYUG9YV0hjYlU1T1kK+KwA+earxS7uSVQ2gc35aOGLe/tTE/7S
        ioMI4CD0S0OoskpsbCweBq3k/hLJ8ZOQNeAge4YR2qX7skpzYvNCsQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-19T06:16:31Z"
  mac: ENC[AES256_GCM,data:vc6WSMgs52/ST3Yh7eN31XNKGUaZH1v+KQ/Iy9Qu+yXSM1+3zrzd4gcutMIRtr6OsHVoBTcc5S+dxSiTbE7INblMvEFf/joM2amv9lWaw33gyZCQYsWfNljyorEX5/IuMEjjgN3db2zpdaV8L66ZFmHPB1CSuaH4boJ14H7FofA=,iv:/L9w6dxTdBoZ+Y1eEcSULijBsqYNu+VIuFo1nua0iSs=,tag:0x7WkNG2FExjxblOmqxshQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
