# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:IuNYY7Mw8KnBL+lXR+72SWtsdxjcM3JEWUh2wkeHJGk=,iv:4NlzJuxfHxwZw9jzy+kbRllBqZ3HwKx/tt0N7oZvFJI=,tag:+8NdYhg2Z1JjTwa/G3oYEw==,type:str]
sops:
  age:
    - recipient: age1ds3pve0r242jp4ktktmx9n3gap5tt37tp3reehtrqp0z0m4ncy7sce4qc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYjlVR3VNTThhM1dGb1Qv
        R2JoTU1TT3ZvZmI0YnFiNkNJQ0FFNzk5ZzAwCm9rMHJCUXdhcW05Um9sczdlN1p6
        cHZmV1VsL3JiU1owaEpIdHRlM3ZXLzgKLS0tIFhpVGVxTGRwV2poSnNpNG03bDNa
        ekVOcFloOVZZOHVLbjlWT0RBSEZIdjgKBOxJS/JPu6PkwZ4XGCSYg8Erm74QfyE0
        5heT73B3Qjd/avABPrv0c6lSHMcciMjdisnjSv0IjOSzJ37oYXlITQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-13T17:26:46Z"
  mac: ENC[AES256_GCM,data:/a2eACl3tF2W8Qtgflc191e9XRt1OnX04G+QqCJWCheGcqEQKm3/RvM9Ls7m3bGudWhdiQ2ZMlIVnu9oz2yTA5qM64oJUg6xljrD2kHVicMOtkT7ye9k4bZnmP4QWYgvHKZqVh+cxcX2B6FKx2mdfx5rUDKnpz3r056Kob0ad1w=,iv:liCl3/hqWfHFvkNy8kixn86Q9FHisJwbEL5q0At66Tw=,tag:Nso8aCqZL/nMOjxPeAHlbQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
