# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:PghQbiiUbNndtj4HYC9yB34kaWfK2WovgiN9sAs9mGQ=,iv:S6lr/wVn+9AzCf03pqeU39+YRFy51JUgeK3r+8mJzvM=,tag:l+ecFR3F6wd/3ujE1D3qkw==,type:str]
sops:
  age:
    - recipient: age1w6awdq3uyjjy9spqc6va5w8m2zfxaa9v7gd43608z2grzcqsef8sagk2yh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbm9LMHJmRmMrQ2hmZnQ5
        RE1OSjJoanNPQzltVXdxM1JCVTRUUE9IY1FFCm9MS3FxZi9zNXhURXNZaHRpWXQx
        WFpxUXRQaUVzR3BhVzBFL2hjcUlkOFEKLS0tIDRVOGdHMHQvNGY0bHBTeEROc0RK
        QkxyNUsvNW9xM0lzazMrSTBBZ040YzgKl7jLp4TZwmKByScVj0P3EYaKP1makoVx
        WWZGcwllcB+F0ttBGtkfaG8rLyhe4rfh3X0WyR7wbQ//ImA7FRRCRA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-08T05:05:28Z"
  mac: ENC[AES256_GCM,data:MUdEpKG8dq9NBdcXj+3IoBMGZEUTU1DxorhEkYD5hNniPCk1l6oa58uySaZZ0JeZ3XEW6WeiMZFtTFiac+et9t+igxJJBcFtuUyp/frYgxRqKc8ZSoKlWFRD8cSkajc7XrbSeOa/WsgxpxKOiB9gJzVetgKPVp6/lQD9eJrcn5w=,iv:H2+siPXTTJxqIiojT6E6BSLjtfMzCf5AlahNQLnkgJM=,tag:D6uw38KU+T9HmiEQzlpMLA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
