---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app oneshot
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      oneshot:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/felddy/foundryvtt
              tag: 12.331.0@sha256:306930efe642caa5541add4e269127a3a9122e007496bb22b524f7d9bcc755fc
            env:
              FOUNDRY_HOSTNAME: &host "oneshot.${SECRET_DOMAIN}"
              FOUNDRY_LOCAL_HOSTNAME: *host
              CONTAINER_CACHE: /data/container_cache
              CONTAINER_PATCHES: /data/container_patches
              CONTAINER_VERBOSE: "true"
              FOUNDRY_TELEMETRY: false
              FOUNDRY_MINIFY_STATIC_FILES: "true"
              FOUNDRY_PROTOCOL: "4"
              FOUNDRY_PROXY_PORT: "443"
              FOUNDRY_PROXY_SSL: "true"
              CONTAINER_PATCH_URLS: https://gist.githubusercontent.com/felddy/a02d66c3817f8223652d96febe580153/raw/foundryvtt-module-check.sh
            envFrom:
              - secretRef:
                  name: oneshot-secret
            probes:
              liveness: &probes
                enabled: false
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: 30000
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 20m
              limits:
                memory: 6Gi
          filebrowser:
            image:
              repository: docker.io/filebrowser/filebrowser
              tag: v2.31.1@sha256:b9b0dcac8b20c01ed4777889c8ae6ff74443ed604e11e4b862d9f3068eeb9114
            args: ["-d", "/db/database.db"]
            env:
              TZ: ${TIMEZONE}
              FB_DATABASE: /config/filebrowser.db
              FB_ROOT: /data
              FB_LOG: stdout
              FB_NOAUTH: false
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 2Gi
    defaultPodOptions:
      hostname: *app
      securityContext:
        # runAsNonRoot: true
        # runAsUser: 1000
        # runAsGroup: 1000
        # fsGroup: 1000
        # fsGroupChangePolicy: OnRootMismatch
        # supplementalGroups: [10000]
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: *app
        ports:
          http:
            port: 30000
      # filebrowser:
      #   controller: *app
      #   primary: false
      #   ports:
      #     fbhttp:
      #       port: 80
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "oneshot.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
      # filebrowser:
      #   className: external
      #   annotations:
      #     external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
      #     nginx.ingress.kubernetes.io/auth-method: GET
      #     nginx.ingress.kubernetes.io/auth-url: http://authelia.security.svc.cluster.local/api/verify
      #     nginx.ingress.kubernetes.io/auth-signin: https://auth.${SECRET_DOMAIN}
      #     nginx.ingress.kubernetes.io/auth-response-headers: Set-Cookie,Remote-User,Remote-Name,Remote-Groups,Remote-Email
      #     nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Method $request_method;
      #   hosts:
      #     - host: "filebrowser2.${SECRET_DOMAIN}"
      #       paths:
      #         - path: /
      #           service:
      #             identifier: filebrowser
      #             port: fbhttp
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /data
