apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:6Me8A1n0xqTFwZIhOTuspIUfaicMQF3NbNtGgHKNz23DVDBtz1v9Fg==,iv:Q6rNLnywk/NbfGiwtLQBdww+SIoNAGJMnurlpaRa1lk=,tag:q6q1AgKksg2zXpandVr26w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmv82du5pq7cddh65lfmwvg3v4ju3pyf99qhnzmhw53mt86vlpyq7ugstq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOT2NMMTFlbVQ5eCsreGoy
            dHlkVWpvUnEvcnM4eWZKSXFFOVZYS0ZhTHc4CnZlU0diNFFpeTZQTjE4ckJxazU4
            Rjgzb0ViNVRFSkNVNncxZ3R6NFdNNW8KLS0tIDFNZ1phblBEanc1Q1lUMk1pYXhS
            QTd0dVRGTzhCWWMrZTJQYUJFaVc1YTAKI/gofj0IFsK/23Vt+ZzmXFwnICWIrGuO
            q5jaLqA6cuRq67Y3hGTLl4TxJqXpTSzfy4m7o+5Krq6wWfbwyvZ6UA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-27T01:14:23Z"
    mac: ENC[AES256_GCM,data:dzJHduYb/ABu8TlnakQSqiX100fsocNyklbenHeevJ2W9FkV8QWqPaynyjj35FrbgtEW1Y2AVOeaUW2Jw89MBvWevAeXjfb1DHhwUJflTXLxp7di/XK+QXklTsYA5uGDCZTUEpCyFfD7qymJxwwltNSNL6ElOx+gVwXcdzM+rrg=,iv:uFtRPFlP78MNUu3xEavNtbamq+lUEgipBOwI5tBwois=,tag:pI6OLavIrV4l4ZmhIFENoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
