# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.32.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:PF1uSuf+1W+Js0IKWx3HX/WbFsuWBO+2dD6/9NJOgahKLXvdk0homQ==,iv:qURtYZPBxn7SpkuwFBujfeFs0m81Am6VjEh62ImR3C0=,tag:lJU+n0KqEzEoLF96D4mWAA==,type:str]
sops:
    age:
        - recipient: age1ds3pve0r242jp4ktktmx9n3gap5tt37tp3reehtrqp0z0m4ncy7sce4qc6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRejdwazZpTkpqWnhqNFov
            akt6bDRmcXAzRXE0UGdLbG9MTkxWbDNEcEZRCmJpT2NDd0lBS1hiSGRzdXB4MDV2
            dzZxeVZTd2ZpRTVRcHZuWjA3Q1IxUEUKLS0tIFJycC9ncERrQTZnejNLS1ZETUNp
            YVJVZVlWT0lHM1RTWnpMNFR1M0FrT2cKZKKvL+lsWkxIu8RiWEdQzDUSgtoyNi7G
            PDXOw7WdWaPq269Wem76x37ItNJVs6doH6ARrKbCSg8Khrd9kTRpwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-13T20:23:51Z"
    mac: ENC[AES256_GCM,data:JbkawNO7qq7nlskf01EJknNDIHAh8A4U1iCLopPJazr4q0NttEJvt6YLe56vmu1lFqF7TMEZPPMiGieR4k++KXQtM9CdePiCgWIJymCfkimzF6qAJNizJq5mGknPqWRphFrygHvp5Cbbs5WsfjLyHAQ/UfmZ6fzTHxkPHk8lErI=,iv:kMj7VPQXNPZ9ZnY2RODqeB4yliSjXZLTB0HdNi3/qV4=,tag:5inmdVbh77BI7pq1hQoXug==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
