apiVersion: v1
kind: Secret
metadata:
    name: bws-cache
    labels:
        external-secrets.io/type: webhook
stringData:
    token: ENC[AES256_GCM,data:Xk+h0N3tppTgz5cDA+9XZ0WcxO/PAyHANXJdZs6OxZyslKiJIjHXe/1JjWeIpsX55sMjKPUyKvvLMW1xJXqMiB6BNWeO7YMsP6TwleF8b0pfcL46lRY6KTJGMkBJBw==,iv:K/nF1r48LMUwwRLpcVXswn3I4VpZfzHcxhej9SdHuDQ=,tag:rVFTTTt9Qb2AU2V26nCmwA==,type:str]
    ORG_ID: ENC[AES256_GCM,data:vF4Io3QCENVh3577vdl9Dmnd7N1KUgEmATsY4iqtHF0mdNQ2,iv:8ZBhTEOFxw/YE/uEEembgCc8/M+qAQOCWJhXgBwmcdQ=,tag:ANh2ynjcRp8VOBSxZ3OxVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmv82du5pq7cddh65lfmwvg3v4ju3pyf99qhnzmhw53mt86vlpyq7ugstq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZ1N2c1FlOWpWeGc4cml5
            NWVpVEV5c011RXIxM3lmYllzeXlYeVJZVFhBCjFMNjdWQlFyKzR0RkZkWXVRUnUr
            cFVuS1FqY0FKZ0JxVlFUeG1Pd1RUN0UKLS0tIHBEaUJXYVJ1NDZuTS9QRnZ1ZUJX
            TE02QWZ6ZzJ5eDFzejVpd09MeHpCdTgKWNUsPhqgEuherU2vkDCy4P/qbp2GDre8
            NClkxwJE02a4TYZ643cR1iVs5WrXry+3LDJ8UhKv25oaom2NfkqwRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-27T02:02:06Z"
    mac: ENC[AES256_GCM,data:LtlGDv90lLK+mlR37CPmRqaCJvXpaDmwG/vE1go7M5VnlgDkbjHRva+G6WpeymoJEzfDf8bsJ3d0gaDzirDoykWFAjXa/2qINNQabdTkWNfLAlmSU9alca9P1nAArzrm3138rsOC09/gB4NoY309ziJ+z2iow9opdophRIOCIWY=,iv:GDQh1vw6d/FRISEpbTHwpZJUuYrAL1VHCB4nE/LMkLI=,tag:X5qKMLJ6UI2JDrcTF/1ddA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
