# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:0FjXNhwQ/NI7kmd53+8HHHoYVz+0oeg/VMegCGN5QJT17mfkb745UEWuyTODR23gGTw6FdqnOcBiSc1IsyqmklpG2CfEtZ8pZsKYRkrRr1jB3JtpNb0yVhsz6mYmz3PGT14wBJEiee0t6f7+b/pkj2UigPWxi8XioSAL9n55wmJbTu/nmtAkv5q/vlVTkukeYPBljh2SmSbxkFWfchu0abbkvtAzJ5CIEUvAAfIG1iMIDdGX,iv:K4iaY0Aby6LLMSHxdQVxuRcfk8FhffZ10OqUfcE6hBg=,tag:wHCU2ebsUxB7IC0pzEfO6g==,type:str]
sops:
  age:
    - recipient: age1w6shr02fugn7ys2cz75f8sq4qcmzuwa6wfwgzx69203zpdaj73ys0ay2ee
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsODNqWmhQNm8rVW1wQ0dq
        N3VIdkJOYnVsMHNyUm5QQkJncS9uMFpXMVdvCjFsaGFsTzdrb0dkcjlXQ01Jd0Jk
        eTFleFlieVZWYU5aZThpWkd6WkN3Q00KLS0tIGRObTB5bko4NkEzVXU5c3lrb01C
        V3hHbml6M2pjaGpjMkRsM2xlSWthYWMKaWVrM+7h3zoCyE008LczdMyMHoduZyIZ
        moLqZo2V6Sw4Q73fGhSJrKpv7EJ7YmdNp+P3MRup9ZUh5+nVb0jbKA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-19T06:16:31Z"
  mac: ENC[AES256_GCM,data:2gamMyUc4sH5o5CFhmU8kwpQDYJTqpNs4RN+OZuphlUSa0unYSMr2Fa8dJEJsrwXF8I9Ezixq9IbZQMr7u+h0cbuGfeVcb7/NTKqNotT+yU2O6jFQ8NMCPE5bh7YZ6+/LSqg2jUgogmmp+yXix8ro2WkoWF5VJ6phS3PYNPPwPE=,iv:ogmmY47SpLILyfzzix/HfHPlL+X+7tTqygRSc4pe7T0=,tag:ROEkxBZiSs2Vlj/i7B3vSQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
