# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:eF/Mox27YVP5AX9wdI5QcT3POkSSMU8IxxzyjyAIy2fxAITjS0O6BHE4DDKCndmZG5kFpNDv1wW06CIyUseCKf6AuM+0Z6KnmUbdbu2O1Ko7HK5t0prQelLtvqUksMrLpH089ZZ03KD/dhZc4gAuY3oX4uHsdijuIAaEqWE8E4pVl9dACRuKI01PcKJ4OnsGPByEJ4XsmGOHhZsCaO7jSx9NjzS4W9ryQTFFN7DxHMaZLYcl,iv:h5zYpCNt312w0FlojerBQxMLyZgLd1bzEX37zs5T8C0=,tag:F9Obt/1XNSsgu3+jB/cAdg==,type:str]
sops:
  age:
    - recipient: age1ds3pve0r242jp4ktktmx9n3gap5tt37tp3reehtrqp0z0m4ncy7sce4qc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWlUzRHZnN3M4akxONU1T
        MmNDZVhIRWxGTkxpMUk2NEs2NXV2eWlZTkI4CldOaUtRTXVkK0FVaE5wVTFCUXVn
        SDRqWkdUV29IbnhWYndCdFBna2k1dncKLS0tIHhBelZTbXhnUmZYck84c0FobDhM
        SUlFUUR6OW5LdkhVUkR2UHI0eUlacDQKXbNsCg6uC9zcMrMTJyLJWDKxKsr6kjfQ
        O3xZXlDtc5B5yXVpjmp5A7IwcS0tkjpIZz3axTH4+2DCKK8d3uTOPw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-13T17:26:46Z"
  mac: ENC[AES256_GCM,data:hwSTaKENj2f5CcEcFve85Z2JLjG+RZS766cAnhzVgXLnOdNrItBfKRaV7gBcPO8n1v1ypq4vVhckPVbizPFfmb3BwEpWV4SVM5bzYv20/0iYPiBOEXb4oyS24ITZGLM5COCtRdSMswEIfUiIFe1DR8V+Qkg/0loTCU7hr5VGWdU=,iv:dLbkTRutFUShw9RHIju1U5/3DW0Id5ISxWabbW6fc0I=,tag:2y+F0lGUKQteHRT4bwrWng==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
