# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:qnpCacqzUfvGBV3vMnRl1UmMujLFqJKR5DWkelq3pgd04lK56NNEClJza15Bl9sbaQe7Z83rQof/M7NvPZDYbfjS9pihu0iRHtyFCVGA8ML0O6C+G8qEp1A20MuItVEm1PbzVJqZP4UtWQHAp73XFqexCSXkQlo08FTUYTYzwf5+/3MxYtoGD6CKrEfa4NpK9Hy9+9rpaJEnuzTZjO7Wov+QTRVBZH1lQoHEz8aftZRBMems,iv:A+NHmrjia0WvUR8Or5ltgpFoIgay/i6hAfvWnlA6pzo=,tag:EC5JazeCkDaM4qWH5505nw==,type:str]
sops:
  age:
    - recipient: age1ds3pve0r242jp4ktktmx9n3gap5tt37tp3reehtrqp0z0m4ncy7sce4qc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdUFsaTJzTDBIZXFqV3Uw
        dHRvL3o0VjJ6emo2L1kxQ0NkaFRkVEJYU3dBCkpKWldEZUNXanVIbTJsZHBlZy9N
        N0hIVWpNV1ZPRitQYzdGSGx2S0laelkKLS0tICtBSlVndlZqY3R0eHZ5OFRKRGxM
        LzdqZTM4QkJCSzZwc2ZiVFl6RHZBdWcKMurKpLYcPAaJNokDh8CO/9eGfQhcM3lG
        DH0ZAqHf/FeTaL7dJkdWvFD2ZcWoEHo2gCSJAynNnJsQV/ACO6w80A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-13T18:08:16Z"
  mac: ENC[AES256_GCM,data:02c/lhgU4MQYNn/53YSjB6QR8uFSraR39jUT4qCEqnZGEbI08EEXGHA3pWEQLENtER3TJClNIh5kXKxfIEm0KdTkQw+pnccL1v6mAO4m1hsDUjdfaodrPOyp5LWYnRNQ3CsnVxSgRDFWrw4gE+SEdHvBd0gsqSE0xcGCaBo0Ofg=,iv:RSYyNYxAAOlUtpVky0ueWjQtFkzvJTe3/W7xDJm2vD4=,tag:UGKXmANkB94KgkRqQAbAFw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
