---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../templates/synology-csi/claims/nfs-downloads.yaml
  # - ../../../templates/synology-csi/claims/nfs-applications.yaml
  # - ../../../templates/synology-csi/claims/nfs-books.yaml
  # - ../../../templates/synology-csi/claims/nfs-games.yaml
  # - ../../../templates/synology-csi/claims/nfs-misc.yaml
  # - ../../../templates/synology-csi/claims/nfs-movies.yaml
  # - ../../../templates/synology-csi/claims/nfs-music.yaml
  # - ../../../templates/synology-csi/claims/nfs-tv.yaml
  # - ../../../templates/synology-csi/claims/nfs-comics.yaml
