---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app drakkenheim
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      drakkenheim:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/felddy/foundryvtt
              tag: v12.331.0
            env:
              FOUNDRY_HOSTNAME: &host "drakkenheim.${SECRET_DOMAIN}"
              FOUNDRY_LOCAL_HOSTNAME: *host
              CONTAINER_CACHE: /data/container_cache
              CONTAINER_PATCHES: /data/container_patches
              CONTAINER_VERBOSE: "true"
              FOUNDRY_TELEMETRY: false
              FOUNDRY_MINIFY_STATIC_FILES: "true"
              FOUNDRY_PROTOCOL: "4"
              FOUNDRY_PROXY_PORT: "443"
              FOUNDRY_PROXY_SSL: "true"
              CONTAINER_PATCH_URLS: https://gist.githubusercontent.com/felddy/a02d66c3817f8223652d96febe580153/raw/foundryvtt-module-check.sh
            envFrom:
              - secretRef:
                  name: drakkenheim-secret
            # probes:
            #   liveness: &probes
            #     enabled: false
            #     custom: true
            #     spec:
            #       httpGet:
            #         path: /ping
            #         port: 30000
            #       initialDelaySeconds: 0
            #       periodSeconds: 10
            #       timeoutSeconds: 1
            #       failureThreshold: 3
            #   readiness: *probes
            resources:
              requests:
                cpu: 20m
              limits:
                memory: 6Gi
    defaultPodOptions:
      hostname: *app
      securityContext:
        # runAsNonRoot: true
        # runAsUser: 1000
        # runAsGroup: 1000
        # fsGroup: 1000
        # fsGroupChangePolicy: OnRootMismatch
        # supplementalGroups: [10000]
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: *app
        ports:
          http:
            port: 30000
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Other
          gethomepage.dev/name: Drakkenheim
          gethomepage.dev/icon: foundry-vtt.png
          gethomepage.dev/description: FoundryVTT
        hosts:
          - host: &host "drakkenheim.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      data:
        existingClaim: cifs-drakkenheim
        globalMounts:
          - path: /data
