---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
 name: &name cluster-user-auth
spec:
 refreshInterval: 12h
 secretStoreRef:
   name: akeyless-secret-store
   kind: ClusterSecretStore
 target:
   name: cluster-user-auth
   template:
     data:
       username: "{{ .WEAVE_USER }}"
       password: "{{ .WEAVE_PASS | bcrypt }}"
 dataFrom:
   - extract:
       key: weave-gitops
