apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:9Z+kUDu21kWSbnjDFtxp2OFe,iv:d0L5MkgidX1RQQGkd8OnviY6ul+NfpNIfoF5W7hurVY=,tag:GeDO8iRiBexQVhk0GI/1rw==,type:str]
sops:
  age:
    - recipient: age1w6awdq3uyjjy9spqc6va5w8m2zfxaa9v7gd43608z2grzcqsef8sagk2yh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdFVybTl1K3l2Y2xmbE1L
        U3A5bkF4UmZsTWRDbVJOVkNmNkNsYlRWTUdVCkx5WHUyWXh0TTBQMWdVZi9QKy9M
        aUhzYVVUeC9VMkw3UGh3Tms5MUhLbVkKLS0tIGRXQVM5QWthU012NHBMSC93RTNp
        TytnemZnSUxYLzU2REZxZUxyUVZCRkUKqjfMenCVRgDuW8qIzt2acb5Fh+c4WbsE
        4mBPcw92kfJavl7Z8fWtDyZQeHHVYcyem5uBueNxbh/9Qa9plUzBsw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-08T05:05:27Z"
  mac: ENC[AES256_GCM,data:IJScux4VYvwVL421E+zqn3pChVcxIPIux6CeabyFmM3UQeh6FOcrwiONeceGagKq7lLmHT2adHQoSwFR2buxELRkcsamHmgLk16e5SBvc6w8yr601bXwELcQ24WKE+xQNEaEgd3AJtYNXRbqictEf5a5k4Ce4vlcN/gsDJitFz8=,iv:SWUNUsISIiXFardxQrbr+ImWXiHIUynoMapLfzD7fvg=,tag:IA8sXznWWJxNH0nYXPDbVg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
