# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:6PzL6EZpZBK5zVgA0/QDMZLuTiIdgjFQdXV95fLqPdEPX2EzMupEYA==,iv:SLr5JmoN8ZStZUs0LWYpTgAIA9YZIW3DuDgBHB3G2Fw=,tag:HPZTcXNgtLjOVSHY3TLS7w==,type:str]
sops:
  age:
    - recipient: age1ds3pve0r242jp4ktktmx9n3gap5tt37tp3reehtrqp0z0m4ncy7sce4qc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocTJEQ2RNNExWeEgvSHlD
        cGVOTWNzcVJ3TXdFa0QwVXEvT3NuQTkxczBrCk9HbGRHWHdpZ3EzUkp6M1dKaUdL
        R2xaQkNCL3ZiMUtLaVVyQjk1alFYeGsKLS0tIHhCRHVXLzJjKyszaVlKSTNwU3hX
        RGdvOXB6R1pJN0FOOUJYRHR1cDNFWjQKNPyr8cG3jXFEXZqrfyJLgh1lt1T6/Wu3
        KFEg6QWv9dkLid6/qMOrMnkbDoSiSjPJ4V4GqH1xwMYkVpNSoxCbIg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-13T18:08:16Z"
  mac: ENC[AES256_GCM,data:gEBvZGl0UpHEFS8spp1c7NPJZ047cPpo/NUkKzCP/kjuHQ8KS9E+63Hg+L4lhxwvOmB8DmGwT3wOj8b1mL9W29Z7ZYyKzvUKuRGbTwMoXRM5rzVP4S57elfllflCzR/s/G8nmyth0/pmegb3MQ2IYamf3MoeEhm+5zvr/LsK9T0=,iv:7Z9szsTAmT4SxhEAc7d5qcjNZOPetyBx+1yMNl/PfHc=,tag:OxX0tETqur2R7+pTTQ351Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
