# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:vQbJEaPZ3W6LAcw0q7z/JauC84gFRt7yo+y0S9bfKD0Nv5cWG1ofJQ==,iv:qQQLMqJnozD6H+TJQH0rkGM02o8z1WXyAzsTkFcu9Bk=,tag:qWTPisvnYYZUHtbZG1Vi2g==,type:str]
sops:
  age:
    - recipient: age1ds3pve0r242jp4ktktmx9n3gap5tt37tp3reehtrqp0z0m4ncy7sce4qc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Nk11RFZhc2FOYnE3K1dt
        Y1JkN2doY2RkMytIQXdySHlIRk9maXl1UFJNCjMyUlltQVdiVi84aEtsTnp4emlk
        VkZKN0haNDl1cjBVSTRYRy9oaVdKNnMKLS0tIEZEOUhOQmFpM1VlTnBtcFlqQkVK
        WTVLa3BwbGxuclN4QURUbmJvLytVRzgK+1UtDnzQBV6EtZxOLFzSVFYZmcUGPEiw
        14xRfeomRL0n5/uCBZYPr40d9/PTz5F3RS4DQy+cf3jLM70AbxnAuQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-13T17:26:46Z"
  mac: ENC[AES256_GCM,data:rfUH6THg6bMtErW5aSH3dclgD4fDJbjTFF/Y7iELRR7V+9tWkyRk7O5u1dflVnHFYo1xwOcz+kofCrb+Q24QOkW4DbpEbjdf6G1btayYxTY4EV/T/LSO8zBKzm9CkllrjhRU8nBrGt5eKOhuYh/6cZ4i9WR4T24k/eG1XTr22+Q=,iv:QB5imKwF1Gx0XMMCbvKqNUqmRLQL/Fp8EOX8rRZp9N4=,tag:SpQZhqXkg57sQLwVsMfUAg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
