# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:4CdFij1bZt9H853Ax+THuRhnubMVI4eAJhjr4duOc8n8CoQVQk7cqQ==,iv:o2BGv64we8GMDprM9wr/GF+Xvybox0GAj4Ncr6M6WAg=,tag:1Ds2tr7tB8iXBxVuVhB+EA==,type:str]
sops:
  age:
    - recipient: age1w6shr02fugn7ys2cz75f8sq4qcmzuwa6wfwgzx69203zpdaj73ys0ay2ee
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaFZyOWp3S2lLV1U1U0xU
        U2U2eUVUVmlPQ0ZKdnIrcnlYVXdZL0RNaWpZCjZzOS9JTlRsTGxnOUtXcW1WOUVP
        VkhDQ1A1dXZ5SzA1V3JmWVdmdlBhaDQKLS0tIE95YWZHSndGN1FWSmZBMTVURE4r
        Tk9vTFZDUGtnL1VGREhWOFN1TGx3QWcKiWXUiRej+6pCZBOt8D4r0ZwDJj/zt+mh
        Wj1FEiW8YCMMvGZMN3a4m9kdzxze2O6qhI00ueSA5GthLwW4+53FVg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-19T06:16:31Z"
  mac: ENC[AES256_GCM,data:KUgTZA8ZBmmfMZd1QzILHqYdL9t6VoBOM78YsG9Bh3yG0CwwmK0N4YdbNQLgPOwAlKBFhj42aGJ9eyYDyyRTlTGhxF8LSWaH7hc2jOgaHP/Mf2USTV2GvHH7iZq4amOynMkTYNk9AUYtaQZxO6ytkVOCyqM/3yhQbrS56hRa3/k=,iv:66HxhoALDDyQiepy+24+eaedHyFAXyhUtTJ/9GumnzY=,tag:aB7mA0C9MQfO0WrMZfEQgg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
