---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: US/Central
  SVC_POSTGRES_ADDR: 10.100.151.35
  CLUSTER_CIDR: 10.69.0.0/16
  SERVICE_CIDR: 10.96.0.0/16
  LAN_CIDR: 10.100.150.0/23
