apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:AG5Sk6oCGjUrVeGA/db2CWXe,iv:BZu1cBxV2wSoFIfD+97jY2NeiWXUYxaLAIHEwc2pESY=,tag:nMRqBdHQrGYJqD7g+2O/1g==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:amxymvCOGVVhSbfQ041L,iv:8pYHyoQ/W5La37tE/Y8meEzX99P9EHNkGZZIq7M0jXY=,tag:5nHEHy0GQ0YPWkwTg0cNxA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:4pZjQML/e7DUJTG4/7pMN7dfuDX2f+Y4QjTX2y3Ugc2ku+vK,iv:/8chN8r4bB5UJOkYcyczeDNFh0gamn0v2KSzTnE+m+8=,tag:+gu1y5G1udZQ7xn9nqM7yg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmv82du5pq7cddh65lfmwvg3v4ju3pyf99qhnzmhw53mt86vlpyq7ugstq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcER2Qjl0WFNQbjl1NFhp
            QzEwWVBEeTFEM2FWVkVzWUxxVTk1bzdmNUQ4CkNlU3pCSUNVVDBQVitYTDJIVTE1
            dFBwUXhDQzhiV0ZoRG51d2ZPNVBYbUkKLS0tIEU5ZjVJNzZNb05OSThDbmQwZkpM
            MGxWdk0wb0VOazN6V2VSK00xVkNMVWcKkTMuampARTtIvoekyp21VhE4g8Bx0rSt
            Xwc6nFNidNDGnNAztswoHC3KZwz/hHRFUVeGzs5BSme9T9Pu3QJrTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-27T01:14:23Z"
    mac: ENC[AES256_GCM,data:2Pshd7OzhOGm9ZNNTMj3FRf/5OPxkMajRiOHIf2Jcb3tEHQMuT6GM+4ngzEs1XIiK1fkXFZ1mMPVh9/I+2vongBgMeGNXOSGjtvUFRbm+YUv7Fn359U4KDnKenffCjSYLOhjTwsFwPMp866Jv0ru+1zU/JwWEx7FXZhgRbVjaxI=,iv:tHbYowjyi1t6O2Abit6GGoGMy+swdeRD0zHHSR5rMRU=,tag:/RMivNFChP8zBMge+MMi5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
