apiVersion: v1
kind: Secret
metadata:
    name: bitwarden-secrets-manager
stringData:
    token: ENC[AES256_GCM,data:Yxhhx67542ojBHjNKgUQLQUYaJFAZ7wyBxeYxiWBj9aN4i4taWCBTOEW1TKz2EBa9yUgbkVAdK+yu27jAe6F2IMn21Rh81EoAKEGNt+vhhMWq21nzQG2SGQhwwPcqA==,iv:K1JOBCP+JVu33Jfx0MMEM6y4EbBXcCNWjCYEvGLa090=,tag:KPVjGNK3Y+w349zihO8HbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmv82du5pq7cddh65lfmwvg3v4ju3pyf99qhnzmhw53mt86vlpyq7ugstq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1QlVSUEFZYTZUbm1PaExO
            WENqci80ZDJIcEMrYVVUVkxGME1OdnhNVFV3CnhuTndtRVZrc290UGdITVBManNN
            MXZaak9GaVdyT1NXdVFXZnFDWE5HakUKLS0tIGl1UG9aUzlKMmNvNFloQ0QzblJa
            aWhzVFpnajIraVIybjQrNlhsOXQxQkEKR760ZudBtD4QKakgf67v5tS40xr8DjKg
            y4wUyJBXNUIAbQnKKLa9wsVf4MMm2JtuKzy4xsDKRrVuIZPKzMuXjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-27T02:02:06Z"
    mac: ENC[AES256_GCM,data:6PkceywOhbq/5RokuTE5j7y6ErW8DriorXzWED2bJS9m37o+eVkoJILEiRIW38L7ROtwGQR6GwsEgPwwFRGEsH/mgKcYzvnUn9MxEqqkuus4srzypgq1BBm2ZLYdB+hXolzgqn5J+Sk3Zy/bWTJLm3bX/OE3ilCNBkWaEYTZr00=,iv:sQo95sQ9nPfo/XdHNygJ6V2t0gAbv2zP/dYZD8VbBwc=,tag:2vTQPq5Ar/NSxFopcrfwIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
