apiVersion: v1
kind: Secret
metadata:
    name: bitwarden-secrets-manager
stringData:
    token: ENC[AES256_GCM,data:ha6un5R2SRGZLgPcl2BNeqgAeDZCyi30PwU1iz7etcKrJ9RBdLxEVrHfIb6tBQxUGYRKS3NHTV8SVrUrfjVCGLFXle1jRUNDx3bAnIYDLeDCBwHMQ+mwKfrhpSca1Q==,iv:YGK5TKMgsfwrr1MQAEL4NLLLVsxZWSzrD2bn9cGyuU0=,tag:8r9ZRsxURAxAqJlYBNPBTw==,type:str]
sops:
    age:
        - recipient: age1ds3pve0r242jp4ktktmx9n3gap5tt37tp3reehtrqp0z0m4ncy7sce4qc6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueVpiTUp1N0gvRnFYbmZK
            RXBtVENMcW9mNjQvSGEwTHYzcjFLclJBa0d3CkR0QUxoRHhjdUdaSWRhcldvaGtq
            SXFvdmlUR2pmaG0yVTNmbWF5MHFCdWsKLS0tIEQrYjRERk44RVY3TXZ0SlhoYm9q
            OGNTbnFtUkJ6QStlLzlhRU84TEU0YlEK6dR9Xtzd0c53VkS3Yi74PzvHBZ711GCJ
            5nYOcW3khBLbTtAc5RYQ+A/GfuEFuaU11SNh1rCNy46BFeJALZR6Tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-15T02:04:50Z"
    mac: ENC[AES256_GCM,data:FGDALYWG4d0+yUOYukHk3MGCJ+8xrtUYMoEf0YcHEQAHZScQfOwqKz3Y6ZiBZRQEnxAHaX45eRXUwiDBAS2jr/2VPmZR4Z281t6lGhZ9x7B4VIMuIbHONuDZqC5h08AtO9mw7ExCdMGMY9eQ92JTTusR5NxS/tcFBrd3yd4MYGg=,iv:6mlbRU2FVPoUmS+HuVhxf5yqtFeu1EqkyvfJVOBJF3s=,tag:nPue019UMFfofLUzAbnFqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
