apiVersion: v1
kind: Secret
metadata:
  name: bitwarden-secrets-manager
stringData:
  token: ENC[AES256_GCM,data:7792oBNxBEsY/QmH+Ks0GRCVrBDcz13f2+PcQpg5BkQnesRDiaSR418afvePjmqjv0Q5PkZz8XnKuogOMe3EuIUFYsF2OmXBOxaZzUZQt8hQq+5CYklW63B9QkXZTw==,iv:Rk9oVLyWvx3XuljZCCbRY2KBr29UbKxSQ9J4FKIr7gM=,tag:DbkMmmJjY+CZQaUW7ga47g==,type:str]
sops:
  age:
    - recipient: age1ds3pve0r242jp4ktktmx9n3gap5tt37tp3reehtrqp0z0m4ncy7sce4qc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueVpiTUp1N0gvRnFYbmZK
        RXBtVENMcW9mNjQvSGEwTHYzcjFLclJBa0d3CkR0QUxoRHhjdUdaSWRhcldvaGtq
        SXFvdmlUR2pmaG0yVTNmbWF5MHFCdWsKLS0tIEQrYjRERk44RVY3TXZ0SlhoYm9q
        OGNTbnFtUkJ6QStlLzlhRU84TEU0YlEK6dR9Xtzd0c53VkS3Yi74PzvHBZ711GCJ
        5nYOcW3khBLbTtAc5RYQ+A/GfuEFuaU11SNh1rCNy46BFeJALZR6Tw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-13T20:35:15Z"
  mac: ENC[AES256_GCM,data:GWh4S8gU6UFz9rSRwC3QWAn9fKs7T04nkkRSb5xzGgEyljiUHE/h2lrzRaU9T9Y/GsQv/ItdknqTdgq/6mUKFlfw7pr26Aidz/op5ebhQfKs2glCNnd0Jos+0sC3LukMUrzPfbq9V+yAlutd8aChTZ+OJ66r/kCJSIB1y26ci+U=,iv:+0dUIHzrW1Ybvp6lC60+tmTvltb7TRi8n7OidJB7F+Q=,tag:9854Z5PtQ988Wm30gCh4Jg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
