---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flood
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: flood
    template:
      engineVersion: v2
      data:
        FLOOD_OPTION_truser: "{{ .FLOOD_TRUSER }}"
        FLOOD_OPTION_trpass: "{{ .FLOOD_TRPASS }}"
  dataFrom:
  - extract:
      key: flood
