---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app flood
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      flood:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/jesec/flood
              tag: 4.9.5@sha256:1a603b5e867aa0018bb1a86882d537469f1ca0cee2860fb3f442cae4445888f6
            env:
              TZ: "${TIMEZONE}"
              FLOOD_OPTION_noauth: "true"
              FLOOD_OPTION_port: &port 80
              FLOOD_OPTION_rundir: /data
              FLOOD_OPTION_trurl: http://flood:9091/transmission/rpc
              FLOOD_OPTION_truser: none
              FLOOD_OPTION_trpass: none
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
          transmission:
            image:
              repository: ghcr.io/brunnels/transmission
              tag: 4.0.6@sha256:95009d4043d3da0084fdfdc1ab4b24a320193c5ca2fd2248153a51d677d6bf8d
            env:
              TZ: "${TIMEZONE}"
              TRANSMISSION__INCOMPLETE_DIR: /incomplete
              TRANSMISSION__IDLE_SEEDING_LIMIT: 10080
              TRANSMISSION__IDLE_SEEDING_LIMIT_ENABLED: true
              TRANSMISSION__RATIO_LIMIT: 1
              TRANSMISSION__RATIO_LIMIT_ENABLED: true
              TRANSMISSION__UTP_ENABLED: false
              TRANSMISSION__PEER_PORT: 60112
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
          exporter:
            dependsOn: app
            image:
              repository: ghcr.io/frantathefranta/transmission-exporter
              tag: 0.3.2@sha256:3e811b044862974548f3685403f4368269223ed5d978f4cf9f8ebb0c9babeaf7
            env:
              TRANSMISSION_ADDR: http://flood:9091
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 50Mi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      hostname: *app
      labels:
        use-vpn-gateway: "true"
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
          rpc:
            port: 9091
          metrics:
            port: 19091
    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
    route:
      app:
        hostnames: ["{{ .Release.Name }}.devilfruitlabs.com"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
                namespace: downloads
    persistence:
      config:
        existingClaim: *app
        advancedMounts:
          flood:
            app:
              - path: /data
                subPath: flood-data
            transmission:
              - path: /config
                subPath: transmission-config
      flood-incomplete:
        existingClaim: flood-incomplete
        advancedMounts:
          flood:
            app:
              - path: incomplete
            transmission:
              - path: incomplete
      downloads:
        existingClaim: cifs-downloads
        advancedMounts:
          flood:
            app:
              - path: /downloads
                subPath: flood
            transmission:
              - path: /downloads
                subPath: flood
