---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app synology-csi
  namespace: flux-system
spec:
  targetNamespace: storage
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
      - name: external-secrets-stores
  path: ./kubernetes/apps/storage/synology-csi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  decryption:
    provider: sops
  interval: 30m
  retryInterval: 1m
  timeout: 15m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app synology-csi-storage-classes
  namespace: flux-system
spec:
  targetNamespace: storage
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: synology-csi-nfs
  path: ./kubernetes/apps/storage/synology-csi/storage-classes
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  patches:
    - target:
        kind: StorageClass
      patch: |
        - op: add
          path: /volumeBindingMode
          value: Immediate
        - op: add
          path: /allowVolumeExpansion
          value: true
        - op: add
          path: /reclaimPolicy
          value: Delete
        - op: add
          path: /parameters/onDelete
          value: retain
        - op: add
          path: /mountOptions
          value:
            - "dir_mode=0775"
            - "file_mode=0664"
            - "uid=1001"
            - "gid=100"
            - "vers=4.1"           # NFS version
            - "rsize=1048576"       # Optional, for read performance
            - "wsize=1048576"       # Optional, for write performance
            - "hard"                # Ensures that NFS retries indefinitely
            - "timeo=600"           # Timeout in deciseconds
            - "noatime"             # Avoids updating access times
