---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/persistentvolumeclaim.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: &name nfs-misc
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: csi.san.synology.com
    volume.kubernetes.io/storage-provisioner: csi.san.synology.com
  labels:
    csi-driver-nfs: "nfs-share"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 12Ti
  storageClassName: *name
