apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:TlX4TSh739vpCXcatCldxSUQ+SkMOjZeI78xmpbLmW4=,iv:es279MdW1RCllnIdc4NRq6dArRGYX6gidQBmfUXXdRE=,tag:/ipOICUJ12JR/BVaqN7Mng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmv82du5pq7cddh65lfmwvg3v4ju3pyf99qhnzmhw53mt86vlpyq7ugstq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MktJUE1zOWZNQUJ1K2tJ
            OWhlMUZZWVk0U1dEV0tlWE5sVnFtc3JaQ1Q4CnF0N0NEN0xCSTZWYk0wbEVOeThj
            NDZJZ3BqSW1hUGYvMTZsdjJ3TjRBa0kKLS0tIHNlS0tNRmljU3VsNGgxZUYyMlY1
            Tm1reHF1WkNsYlJ5ZTVJblVuNU9pRTQKUCHFacwTMf67nTwcndSSFJiBBHs1snTk
            sYSuU5MxAJN9IUvBvcyauKK1RHsEzXCwQ9rp1z97GwMdO8ihQk1azw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-27T01:14:24Z"
    mac: ENC[AES256_GCM,data:PAK8PBXM6PE5pBDDBfn8RdpaQHZpJNvsEfTBRSLxsKa2IHsW8nEw3m/ViSi2NB1kUJ0ZuM7RtfDuK8E+kPzkJzG7ZIevrkWwDHM8ghd4v4AdwZ/CHCocCHdJ5pDcbYYeSGFi+COXf1uW1c85JerjvFtGmypMcHgApNgA84FKaKQ=,iv:GXouVjfRj7qxbLdU3EyAYTMxjXfR2Px3ZenxUrUB9KQ=,tag:8IUf0sUa5Fke2srtu3CKpw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
