---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name mealie
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # App
        POSTGRES_SERVER: &dbHost postgres-rw.databases.svc.cluster.local
        POSTGRES_PORT: "5432"
        POSTGRES_USER: &dbUser "{{ .MEALIE_POSTGRES_USER }}"
        POSTGRES_PASSWORD: &dbPass "{{ .MEALIE_POSTGRES_PASSWORD }}"
        POSTGRES_DB: &dbName mealie
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_ADMIN_PASS }}"
  dataFrom:
    - extract:
        key: postgres
    - extract:
        key: mealie
