---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/job.json
apiVersion: batch/v1
kind: Job
metadata:
  name: cloudnative-pg-restore
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      automountServiceAccountToken: true
      restartPolicy: OnFailure
      containers:
        - name: postgresql
          image: ghcr.io/cloudnative-pg/postgresql:17.4-9@sha256:507376cb4fb29498d767fbc1ed5c3a9ee6099136d3519be69bdb463b92b5120e
          command: ["/bin/sh"]
          args:
            - "-c"
            - "gunzip < /backup/${SECRET_DOMAIN}.cloudnative-pg.dump.gz | pg_restore -U $PGUSER -f -"
          env:
            - name: TZ
              value: ${TIMEZONE}
            - name: PGHOST
              value: postgres-rw.databases
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudnative-pg
                  key: password
          volumeMounts:
            - mountPath: /backup
              name: backup
              subPath: cloudnative-pg
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
      volumes:
        - name: backup
          persistentVolumeClaim:
            claimName: cifs-backup
