---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app drakkenheim
  namespace: foundryvtt
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: volsync
      namespace: volsync-system
    - name: cloudflare-tunnel
      namespace: network
  values:
    controllers:
      drakkenheim:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/felddy/foundryvtt
              tag: 13.345.0
            env:
              FOUNDRY_HOSTNAME: &host "drakkenheim.${SECRET_DOMAIN}"
              FOUNDRY_LOCAL_HOSTNAME: *host
              CONTAINER_CACHE: /data/container_cache
              CONTAINER_PATCHES: /data/container_patches
              CONTAINER_VERBOSE: "true"
              FOUNDRY_TELEMETRY: false
              FOUNDRY_MINIFY_STATIC_FILES: "true"
              FOUNDRY_PROTOCOL: "4"
              FOUNDRY_PROXY_PORT: "443"
              FOUNDRY_PROXY_SSL: "true"
              NPM_CONFIG_CACHE: /data/npm-cache
              NPM_CONFIG_PREFIX: /data/npm-global
              CONTAINER_PATCH_URLS: https://gist.githubusercontent.com/felddy/a02d66c3817f8223652d96febe580153/raw/foundryvtt-module-check.sh
            envFrom:
              - secretRef:
                  name: drakkenheim-secret
            # probes:
            #   liveness: &probes
            #     enabled: false
            #     custom: true
            #     spec:
            #       httpGet:
            #         path: /ping
            #         port: 30000
            #       initialDelaySeconds: 0
            #       periodSeconds: 10
            #       timeoutSeconds: 1
            #       failureThreshold: 3
            #   readiness: *probes
            resources:
              requests:
                cpu: 50m
              limits:
                memory: 6Gi
    defaultPodOptions:
      hostname: *app
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        ports:
          http:
            port: &port 30000
    serviceMonitor:
      app:
        endpoints:
          - port: http
    route:
      app:
        hostnames: ["{{ .Release.Name }}.devilfruitlabs.com"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
                namespace: foundryvtt
    persistence:
      data:
        existingClaim: cifs-drakkenheim
        globalMounts:
          - path: /data
