# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.32.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: akeyless
stringData:
  accessId: ENC[AES256_GCM,data:qWv1+RFMaxbxOkFnfzo+7g==,iv:gK/BfbNpCPaNtbUA8Efw5aNh6+k68UEoY4r72JrTvT4=,tag:F80zOkhqwEdgjHG+mArjQQ==,type:str]
  accessType: ENC[AES256_GCM,data:kFGDRqJtTg==,iv:vKyqEh9LFyWrJZ0hAh+NEpjlTl4BN9rsYACcWiEbHOM=,tag:VWTMeyEKaJp6rtVRjVOmdA==,type:str]
  accessTypeParam: ENC[AES256_GCM,data:ndZgN7E47NQll9ACBifqa/aUQTT0d6/sfX7IVL1819k/WqKoTfcbd2smRc0=,iv:sn9n5YJk6Q+hCuvPy0k4z7ruartKwNZFk3EyIUyQog0=,tag:iVvrHtssZcO8WWRCfJfBXw==,type:str]
sops:
  age:
    - recipient: age1ds3pve0r242jp4ktktmx9n3gap5tt37tp3reehtrqp0z0m4ncy7sce4qc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0K2RubU8vVU9WTCtBTlRl
        QWxGQ3N0ZjlOTVhMakJ2cE93VjloNXVEN2lFCjFIL3g4RDNwbmhodzEvYmd1ekNW
        MDVIRjY1NmlWSHVtcm82YTdQdFZVMkEKLS0tIEVjdlA3OGVPQUE3VW56b3NLT0Zn
        NWVUZmx1UlFpWUFCajY5TERMWlZiUzAK60anya5OD8s6VDgfURnsIGE68MlfPCeL
        XSp4Dg6Rvzi2i/Tt5gLchewsyQStxLuwZmlKQB216mTYS0cZFoO5Xw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-15T15:28:43Z"
  mac: ENC[AES256_GCM,data:Vim2ceLTPaJx9E0JkuTPUMVJvrWQSWOzw/Ms99wrA3lOUZ7fPMZWEVqjIQ2xMCfZeRhZbtPd46YRwbNyFXvkqjJXagXvpkqZeEq8jwiy0F1UvyTjcmlVOYytiOrsUnmhghDmZm0fRy0qRHpYFxhB9rIu6lgBnavoHMfG36WdDUc=,iv:J/HpbDpSb/arQjOYYCuk3ASKSf5hiVy9k8NVwj0NEhM=,tag:jYboDuxIfABg8uA91oUS6g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
