# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.32.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: akeyless
stringData:
  accessId: ENC[AES256_GCM,data:7xEHcJMAERm9scLRvpaFOw==,iv:Qh2NTWjwUl8YufweqCsiZp3qYQ2gzlhwzg2eIFpJzvw=,tag:W0NG8njs0UBn/ibkLfsU5A==,type:str]
  accessType: ENC[AES256_GCM,data:1SsUtHYpvg==,iv:oqCk9IXYMhhGQsqbq2/0aRl4kb/RIygLlLKECcvZOiY=,tag:W16Mpel2rCpIIiOPqsZJIw==,type:str]
  accessTypeParam: ENC[AES256_GCM,data://rR3X/OklAUJesH0xYMtE/zmNbuzUaFBJ1jFPLqvBUWk74IfBeZFslCdx0=,iv:xyP4c+KA3Iq3YK43p9PjB/BpHBGswq3+DvvLlpfXDXM=,tag:xmFZFVpjB/u+m/X9RGt8nQ==,type:str]
sops:
  age:
    - recipient: age1ds3pve0r242jp4ktktmx9n3gap5tt37tp3reehtrqp0z0m4ncy7sce4qc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtU1ZnTjZzY28zcjlXeUNN
        RmFJVmJaZ2pzMWpieEpkSGFDakxZV3c0eEdVCjBKMWU3bzdacklIbytMVHc4RFlt
        eVI4OU11SXVYWU1UVUVXbG9KYmtkMjAKLS0tIG1jU2RpS2VUYkppemI5cUZrOWg4
        c1p5aEdwWmVrK29XVHpKQjRFNzB0VUEK68LeYe/gxjJ3J0pk3/s3QFEiVBDqB5UU
        UJn2ctgBOaElr3pCoSVgbXoF2jY4lXzA060Qvbf9Dtti9bvvNWekyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-15T14:51:57Z"
  mac: ENC[AES256_GCM,data:xoyJYjci3OIlvaZFNkkwgSfmDg3l6ehKcSK+heYO4f1ZP1+YehLx91Jfh3Vwhek76o35CUfuuKo/TUkT25H5N0srK0S4BlEYH2hs84E/N22bAaNj0vA3qd6PBKA/NWVn59Yp4FZns2hYWmlKiXm6zdLecWJIOSwgvSFD//4E5s8=,iv:AUWvXMbMSFAKCbakWyyVTgqvpWR1FPeyrXf826QCzlc=,tag:R3mYlLS39UfiZ6LiBXErCg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
