# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.32.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: akeyless
  namespace: external-secrets
stringData:
  accessId: ENC[AES256_GCM,data:1RPsCN9ZkKRBy+CxjAJXdA==,iv:Z6H4fjI6TDWHsVqAKEBFzIvHIen4jSLJdtYCLOcro8Q=,tag:044NFzmbQ9SQvKP9nKFXEg==,type:str]
  accessType: ENC[AES256_GCM,data:x7KiCt2O5Q==,iv:OzBCi+ONF9n3YUC7pl+L74CGwamQAw93rbjnVg8Epcs=,tag:lWzAY0fTV049OH/74asUkQ==,type:str]
  accessTypeParam: ENC[AES256_GCM,data:SMtZtEx0lc6F+QONssBWVPe1xyzUNFEXbfBf6H9X/RdUhdEHTDfmMoCBG1s=,iv:nkSfNtbsjl2alMvXEEN9LSKeGvtcfBHwapUvXbV3jBc=,tag:JIpPrEH/HtwLiZCrgjOxJA==,type:str]
sops:
  age:
    - recipient: age1w6shr02fugn7ys2cz75f8sq4qcmzuwa6wfwgzx69203zpdaj73ys0ay2ee
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEalU5Qjh1NGZ2dy9IZHQ3
        RFlBTWhNR1c5NGRoZjFaaGRnbEdlQWpweUZNClpCNzBSOHlrc0hsMm5uNmJRTzho
        WFYxQXFPT21Kc2lvZWI1Y1R6Vnd6U28KLS0tIEhTakpvWEMwdFJEb1cwc0VYbkNW
        cmluOEtmalQzZ2N3aTZ6bkJQSjliUGcKPk18axBktxowSMfCxQRc14mD9RWF82qB
        tJD1fkVG2ap9aqPgn2umpAVKukSxtvwr1q90zx+AFeeRn3AUH+wDpQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-19T06:38:16Z"
  mac: ENC[AES256_GCM,data:9jguvMCyqPSWbSxDV9zWzzJfVnjPonKnWou7zBOOleVfViufMjUbf/aLhDBWveUA6g2GQstV152lvzD6Uyq2liyt9arV5k+t71ePfRr/2m8K0lPtH+YXYzP7kD3/5RDGx/pfi1erLsxZBPxiJygHNizyK0f3VESTjvG4LghQhWc=,iv:GtdeY3pp0o4OymzjNRqrrsahICnNcC8A4FQyZ9NSLrY=,tag:iL1zP2ugmeAPA+KBo2gRKA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
