---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/storageclass.json
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "nfs-movies"
provisioner: csi.san.synology.com
parameters:
  server: "${SYN_HOST}"  # NFS server hostname or IP
  share: "/volume1/data/movies"                 # NFS export path
mountOptions:
  - vers=4.1                        # NFS version
reclaimPolicy: Retain               # Reclaim policy can be changed to Delete if needed
