---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app bazarr
  namespace: flux-system
spec:
  path: ./kubernetes/apps/downloads/bazarr/app
  targetNamespace: downloads
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  prune: true
  wait: false
  interval: 10m
  dependsOn:
    - name: cloudnative-pg-cluster
    - name: downloads-cifs-pvcs
    - name: volsync
  postBuild:
    substitute:
      APP: app
      VOLSYNC_CLAIM: bazarr-config
      VOLSYNC_CAPACITY: 2Gi
      VOLSYNC_CACHE_CAPACITY: 2Gi
