apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:U3zv70CRP2Wvy5SRwxqV/bns,iv:dnQ7EQxiVRBLcNTch2wzOm6DJpk85fJANPVUHhnGIQc=,tag:IePI2nRRW6YEeboOkTXxNg==,type:str]
sops:
  age:
    - recipient: age1ds3pve0r242jp4ktktmx9n3gap5tt37tp3reehtrqp0z0m4ncy7sce4qc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2am83d1ovTkJnUyt1eDFW
        VzhFTU02RVhSTEFiTGpWeXAwaXJkMG5BTncwClRVc0gvTks3V2ZldWRVN21sMTda
        M1hScVlNcC9SUjhLNEN4M3RaNjU5Q2sKLS0tIHZLRWh1VUxLMFhvMHBUMmRxanJ2
        STBHVlp3VDFDZEVBUDRIdzFaWjFoRW8K504QD5NRlswc3AkGYHp6WMzJ0H9Gj+cO
        56V4TomGnxaM8DqDaXiFCy2xJbzTo3gd/IlqOU49LBPp3YeFuoSHtA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-13T18:08:16Z"
  mac: ENC[AES256_GCM,data:2zo3pGIDaSYZZfnEeHgPfjEankoOzIeua/b0u9+uoP6VV19NPgRXkPLMyxakvV9Q8vf0DQc/avObw6Pla0hwy3/2Nf4yAowFUHOVMEh9qHE7l/e+3j47eANS3XpqyMXZk/bd+yhwa+qCtV4ufmMNK/LvKQgPpJn6wX8Li79pOx4=,iv:v0LTnStlXKvH95HA03i8jrNeyfj9pQ+nAJiiptMkwtw=,tag:zKiWralg8ZVPov1Zfueexw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
