apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:um1SDKdBWgcmQ2uTcRx+1XYW,iv:YyFoj6EIQxVRssjgVXQDkB9SFlXh7VH3nUYS9wQaMxU=,tag:v1UrNhjxT0izMxYfLh/3Ow==,type:str]
sops:
  age:
    - recipient: age1ds3pve0r242jp4ktktmx9n3gap5tt37tp3reehtrqp0z0m4ncy7sce4qc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZTFUZFBHdVoyL3cwY0VU
        L3hLVFdzR0ZROVRVZzY5bmZoOERraDJlU0hZCm5rZE5OdUovZGpEeVRDZWNiOStt
        anVYUXlLelJKQ2RrWGpvT3B4MnRXNTgKLS0tIGlZSklNcDVsV1JWT0lmOEIycUdl
        Y2VxcXVPbFBJKzVKc3FaNlJLOFZuSWsKaX+REvM8hBph27RBex2Yt2mR5aw2KZCP
        NL4QrkTtUwWa8S9eC25jGwi2z8tqMwoFsBAaQVEO9QgvkZ8TWuzIKg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-13T17:26:45Z"
  mac: ENC[AES256_GCM,data:ctJ5iWvRkB0ISO/trpwjwha4ghX9ZSsf0LfRwNh8rKQj4WB+ryV+nqTBRtQkN4M7ouAWY67eD3pbNCnLy9wyHXRhf4LxPhnRnPhRsBy68Y+6dmhDS+Z1WE5RwCpGaJgK31cIs1A+C+yG6+AaTqjiR2NPdmgmDZV4uJAQkPXurxA=,iv:o31oQjcMSV2pYdE0YGONBKnb8/hzLyN9AvunZWgm8/E=,tag:0zBOw040kPt3ZMq+4bluyQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
