apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:Y29BTQQooh6IuYaSR0a68qm37xaJ0ZAycgS8H06zIUxR+Dn8HjGtkGR6fUkVkHGtoI435LK+m0l4CQhll6usGBQF5KmrwGiQEWs=,iv:i2sDJH3I6WWRjniMX/R7B1aZQFNJiJbI5KDmcm+CHkc=,tag:YN0pORMIBkU++XK7sAbifg==,type:str]
sops:
  age:
    - recipient: age1mfruhqf220mfpp4wgxzg4mmy9enethvemn2uyk5v3tutlcm0mensgnu5qu
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNT2NycWNYMmdpQ0l4dGh2
        Uzl4OU9GRVJIRU9iN2JlRGl5bk1JTnA5YndVCiswTEhXeWRUQUxiajBoOWtNUGdj
        enk5ZXFvQXpza2lBd0JlKzQ1a2JEeVUKLS0tIHpDYlBJQVMvRHBxSno5YzVHTHQ1
        elVpUHhRRGNLRWM5UThMdXRNOFNmbDgKfyRkjmvWn/MD28TxN4NmJPBa7hiRlCgD
        PxvWooMLp/7Za++34PWulxuZFJqWOse3nc37aXbFaDTEmupSplm8Kw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-01T14:47:49Z"
  mac: ENC[AES256_GCM,data:U+/tZIyw3669yubN8OGotk3tlDyxwFTRAOYKLByevv2SjNE9iA8CK/FxIwEPqenEWuQ7gisqUPTQMygSbmVPb7aaV/ZsR7RbcfSRFCAzN0hEaKgX6LjB3H7636fnfKBcetNfiOn0YwHsRkjTZxzuTj57ee9FHGB9vATpm28gYfg=,iv:NXPLfDvaz8KkyrEeCZk63jqr295mKZkzuKpMLvKHBZI=,tag:OHM2fLIZ4s2JANy1fqtzCQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
