apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:wMEg3aFTG2sQqnPxooZ5YvNXDi0aoPs26P2bUvt1EMozw2kGzejLYNuIIMMO7FsUKdDjSOOTlcO0gFskjW1qkNh6h2ltwhZ1ES8=,iv:M1HTsJsPnB90B+uU7jzV96IN3XY+ZHnA6otmsf42gYk=,tag:tlDRkehrmxsZt6itmGYI+g==,type:str]
sops:
  age:
    - recipient: age1ds3pve0r242jp4ktktmx9n3gap5tt37tp3reehtrqp0z0m4ncy7sce4qc6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVY3Z2UTMrV1BQZExheUlj
        TFFtVEpRQUxBWnJZU2luYkpTMmlGVS80bWhzCk5UTTY2WUZvM2NZUW96eXFVT29x
        WmczeHQwLzh3bUdnRzNsTXFJc3M4b28KLS0tIGJmcVRITmdSOTFxTlZVeEdWRng2
        VmtNcFcwNUkxc3QydzlyUmU3cE1rTEEK2OYQcC8tcsOb8jjtcmee9wXJK4RA6Kmo
        /ZdiQELsPifvCwSHYAlr0YBbqkBw5Gf0xh+psBjTycosMeJqA/0XHA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-13T18:08:16Z"
  mac: ENC[AES256_GCM,data:jhKHCRQ5o4MAUif+nL+4gz5QDEu50W59TIZ29XFEqiUmtABER3JyDKfCFvAuGkkx7gVWUuaSdRudXHfQSIzsgigocsqHffkoxJHLZC4eCy3DdWf779WdifcbACI3WbnCp364odOC6do+uL5A2BlDobtEufH/l70qyzotxvZdXJU=,iv:RRKusB7mAfyBp1srUwEYWYbuDWBgN1zVnPoqbCDsUho=,tag:eJUc9KA3jq5KltLAdJjyUQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
