apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:y0ZcZhxqxt3vqjQxhui0GQRwuAfavFffAwYZ497S2XuxmlT+fOqD4g==,iv:rY+42ABl4mTYmFxRYU1B/bMZBBuX9ZL/vtPHFW4bovg=,tag:2sPu6GjXD/Dd7wPcOjxMwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dmv82du5pq7cddh65lfmwvg3v4ju3pyf99qhnzmhw53mt86vlpyq7ugstq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5OGt1bUE4U2phVVVKZDRT
            YWdXVWJwU2VxOGk4c0ZnVFFBYkowN0c4aWk4CkxndW5BSjNEVlczSndaZmdQVlRt
            WjVCM1p3OFR6cjVLSEZ2ODRrelQyRTgKLS0tIHc1eGNhditpYnZpT2p6eGduV2ZP
            SGloYldCbnRvY1VReld3NzJYVFF6blkKEBiEtRac0MbGO+ba4QQcJsEGeB0v03hg
            FeNJZPulb+XLSC6xC3J7569jR0pch8IOx+e9jkY0jxe0+9o6Tk27qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-27T01:14:24Z"
    mac: ENC[AES256_GCM,data:dMO8pEj/bd4A7yo7vQNNcEEwaYOZoe6n28EGB76gUzs3bpdZNJTsEwTFvm4yoemfiKW0JKbhNA+fvhWLCmyYbO7Uu1+qOPL7kl9kvjYeujKjS2lYb21+B+M7Uy45NOZ0q3Z5zo2ZQdQj4BMTPiPAFs/4VAshMdIYGzXx4D6cvk4=,iv:PXTn5vBxMQdFmEqSYFHyVLhfPKntJwb58wfTxGi/fjs=,tag:beghg0142OSjqGaRnh+Z4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
