---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wiki
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bws-cache
  target:
    name: wiki
    creationPolicy: Owner
    deletionPolicy: "Delete"
    template:
      engineVersion: v2
      data:
        DB_PASS: "{{ .WIKI_POSTGRES_PASSWORD }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: wiki
        INIT_POSTGRES_HOST: postgres-rw.databases.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .WIKI_POSTGRES_USERNAME }}"
        INIT_POSTGRES_PASS: "{{ .WIKI_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_ADMIN }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_ADMIN_PASS }}"
  dataFrom:
    - extract:
        key: wiki
    - extract:
        key: postgres
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name wiki-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bws-cache
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        displayName: Authelia
        clientID: "{{ .WIKI_OIDC_CLIENT_ID }}"
        clientSecret: "{{ .WIKI_OIDC_CLIENT_SECRET }}"
        authorizationURL: "https://auth.$(SECRET_DOMAIN)/api/oidc/authorization"
        tokenURL: "https://auth.$(SECRET_DOMAIN)/api/oidc/token"
        userInfoURL: "https://auth.$(SECRET_DOMAIN)/api/oidc/userinfo"
        issuerURL: "https://auth.${SECRET_DOMAIN}"
        redirectURL: "https://wiki.${SECRET_DOMAIN}/login/77b50f16-0381-433e-b328-27c373ea5f83/callback"
        emailClaim: email
        usernameClaim: username
  dataFrom:
  - extract:
      key: wiki
